/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-anime-sky-56a60c1d1e8b44eabff138374f996d8f
Title: FREE - SkyBox Anime Sky
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three";

export function AnimeSkyBox(props) {
  const { nodes, materials } = useGLTF('textures/skybox_anime.glb')

  const texturePandoraBG  = useTexture("textures/pandora_diffuse.jpeg");

  texturePandoraBG.flipY = false;
  texturePandoraBG.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texturePandoraBG,
    opacity: 1,
	// transparent: true,
	// color: '#fff'
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
        //   castShadow
        //   receiveShadow
          geometry={nodes.Sphere__0.geometry}
          material={textureMaterial}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={7000}
        />
      </group>
    </group>
  )
}

export default AnimeSkyBox;

useGLTF.preload('textures/skybox_anime.glb')
useTexture.preload('textures/pandora_diffuse.jpeg')